name: Build React Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd AWS_Client_CAC_Avatar_2.0
        npm install --legacy-peer-deps

    - name: Build React App
      run: |
        cd AWS_Client_CAC_Avatar_2.0
        npm run build 
